let tex = ['hello','owu','com', 'ua'];
console.log(tex);
alert(tex);
document.write(tex);
let num = [1, 10, -999, 123, 3.14, 2.7, 16,];
console.log(num);
alert(num);
document.write(num);

console.log(true);
alert(true);
document.write(true);
console.log(false);
alert(false);
document.write(false);
let firstName = `andriy`;
let middleName = `moroz`;

let lastName = `mukolayovuch`;
let datum = 1991;
let person = [firstName,middleName,lastName,datum];
console.log(person);
prompt(firstName);
prompt(lastName);
prompt(datum);
let a = 100;
console.log(typeof a);
let b = `100`;
console.log(typeof b);
let c = true;
console.log(typeof c);
let bool1 = 5<6;
console.log(bool1);
let bool2 = 5>6;
console.log(bool2);
let b3 = 5===6;
console.log(b3);
let b4 = 5>=6;
console.log(b4);
let b5 = 10===10;
console.log(b5);
let b6 = 10>=10;
console.log(b6);
let b7 = 10!==10;
console.log(b7);
let b8 = 10>10;
console.log(b8);
let b9 = 10>10;
console.log(b9);
let b10 = 123>`123`;
console.log(b10);
let b11 = 123==`123`;
console.log(b11);
let str = "20";
let l = 5;
document.write(str + l + "<br/>");
document.write(str - l + "<br/>");
document.write(str * "2" + "<br/>");
document.write(str / 2 + "<br/>");

